force-app/main/default/objects/Quote_Express__c/Quote_Express__c.object-meta.xml
<CustomObject>
    <label>Salesforce Quote Manager</label>
    <nameField>
        <label>SQM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Quote Manager</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Express__c/fields/Additional_Sales_Contact__c.field-meta.xml
<CustomField>
    <fullName>Additional_Sales_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Additional Sales Contact</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quote_Express</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Express__c/fields/Automotive_Programs__c.field-meta.xml
<CustomField>
    <fullName>Automotive_Programs__c</fullName>
    <inlineHelpText>Combination of Program Name, OEM &amp; Platform.</inlineHelpText>
    <label>Automotive Programs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Program 1</fullName>
            </value>
            <value>
                <fullName>Program 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Express__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Quote_Expresses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Express__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Express__c/fields/PCS_yr__c.field-meta.xml
<CustomField>
    <fullName>PCS_yr__c</fullName>
    <label>PCS/yr</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Express__c/fields/Quote_Currency__c.field-meta.xml
<CustomField>
    <fullName>Quote_Currency__c</fullName>
    <label>Quote Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Express__c/fields/Quote_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Quote_Due_Date__c</fullName>
    <label>Quote Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote_Express__c/fields/Quote_Status__c.field-meta.xml
<CustomField>
    <fullName>Quote_Status__c</fullName>
    <label>Quote Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Express__c/fields/RFQ_Date__c.field-meta.xml
<CustomField>
    <fullName>RFQ_Date__c</fullName>
    <inlineHelpText>Request for Quotation Date</inlineHelpText>
    <label>RFQ Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote_Express__c/fields/RFQ_No__c.field-meta.xml
<CustomField>
    <fullName>RFQ_No__c</fullName>
    <inlineHelpText>Request for Quotation Number</inlineHelpText>
    <label>RFQ No.</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Express__c/fields/Terms__c.field-meta.xml
<CustomField>
    <fullName>Terms__c</fullName>
    <label>Terms</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Line Item</label>
    <nameField>
        <displayFormat>QLI-{0000}</displayFormat>
        <label>QLI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Line_Item__c/fields/Automotive_Programs__c.field-meta.xml
<CustomField>
    <fullName>Automotive_Programs__c</fullName>
    <inlineHelpText>Combination of Program Name, OEM &amp; Platform.</inlineHelpText>
    <label>Automotive Programs</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Program 1</fullName>
            </value>
            <value>
                <fullName>Program 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <formula>Quote_Express__r.Customer__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Customer_Part__c.field-meta.xml
<CustomField>
    <fullName>Customer_Part__c</fullName>
    <inlineHelpText>It represents the specific number of the part produced/manufactured</inlineHelpText>
    <label>Customer Part #</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Developer_Charges__c.field-meta.xml
<CustomField>
    <fullName>Developer_Charges__c</fullName>
    <label>Developer Charges</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Part_Description__c.field-meta.xml
<CustomField>
    <fullName>Part_Description__c</fullName>
    <label>Part Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/PCS__c.field-meta.xml
<CustomField>
    <fullName>PCS__c</fullName>
    <label>PCS</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/PCS_Yr__c.field-meta.xml
<CustomField>
    <fullName>PCS_Yr__c</fullName>
    <label>PCS/Yr</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Pieces__c.field-meta.xml
<CustomField>
    <fullName>Pieces__c</fullName>
    <label>Target Price/M ($)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Production_Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>Production_Lead_Time__c</fullName>
    <inlineHelpText>Working weeks which takes to finish the production process and it won&apos;t include the period in which process starts.</inlineHelpText>
    <label>Production Lead Time (Working Weeks)</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Quote_Express__c.field-meta.xml
<CustomField>
    <fullName>Quote_Express__c</fullName>
    <label>Quote Express</label>
    <referenceTo>Quote_Express__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/RBW_Drawing_Number__c.field-meta.xml
<CustomField>
    <fullName>RBW_Drawing_Number__c</fullName>
    <label>RBW Drawing Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Sample_Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>Sample_Lead_Time__c</fullName>
    <inlineHelpText>Working weeks which includes Pre and Post processing stages once order is placed</inlineHelpText>
    <label>Sample Lead Time</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote_Line_Item__c/fields/Standard_Pack_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Standard_Pack_Quantity__c</fullName>
    <label>Standard Pack Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Standard_Clause__c/Standard_Clause__c.object-meta.xml
<CustomObject>
    <label>Standard Clause</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Standard Clause Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Standard Clause</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Standard_Clause__c/fields/Clause__c.field-meta.xml
<CustomField>
    <fullName>Clause__c</fullName>
    <label>Clause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Standard_Clause__c/fields/Quote_Express__c.field-meta.xml
<CustomField>
    <fullName>Quote_Express__c</fullName>
    <label>Quote Express</label>
    <referenceTo>Quote_Express__c</referenceTo>
    <relationshipLabel>Standard Clause</relationshipLabel>
    <relationshipName>Standard_Clause</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/printPreviewController.cls
public class printPreviewController {
    public static Quote_Express__c quoteExpress {get;set;}
    public static List<Quote_Line_Item__c> quoteLineItems {get;set;}
    public Boolean isApproved {get;set;}
    public string formattedDate {get;set;}
    private static ID RecordId;
    public string userEmail {get;set;}
    public string userPhone{get;set;}
    public string clauses{get;set;}
    
    public printPreviewController() { 
        try{
            RecordId= System.currentPageReference().getParameters().get('id');
            userPhone = '';
            quoteExpress = [SELECT Id,Name,Customer__c,Phone__c,Createdby.Name,Createdby.phone,Createdby.Email,Additional_Sales_Contact__r.Phone,
                            Additional_Sales_Contact__c,Additional_Sales_Contact__r.Email,Contact__r.Fax,Quote_Status__c,Email__c,RFQ_No__c,Terms__c,
                            Automotive_Programs__c,Quote_Currency__c,Quote_Due_Date__c,RFQ_Date__c,Additional_Sales_Contact__r.Name,
                            (Select id, Clause__c  from Standard_Clause__r where Active__c = true LIMIT 1)
                            FROM Quote_Express__c 
                            WHERE id=:RecordId  ORDER BY createddate DESC][0];
            quoteLineItems = [SELECT Id,Customer_Part__c,PCS_Yr__c,PCS__c,RBW_Drawing_Number__c ,Developer_Charges__c ,Part_Description__c,Standard_Pack_Quantity__c,Pieces__c,Sample_Lead_Time__c,Production_Lead_Time__c 
                              FROM Quote_Line_Item__c 
                              WHERE Quote_Express__c =: quoteExpress.Id];
            if(quoteExpress.Quote_Status__c == 'Approved'){
                system.debug('line 13==' + isApproved);
                isApproved = True;
            }
            system.debug('line 16==' + quoteExpress.Additional_Sales_Contact__r.Email);
            String FileName = quoteExpress.Name +'.pdf';
            if (quoteExpress.Additional_Sales_Contact__c != null) {
                userEmail = quoteExpress.Additional_Sales_Contact__r.Email;
            }
            system.debug('line 25===' + quoteExpress.Additional_Sales_Contact__r.Phone);
            if (quoteExpress.Additional_Sales_Contact__c != null) {
                userPhone = quoteExpress.Additional_Sales_Contact__r.Phone;
            }
            if(quoteExpress.Standard_Clause__r != NULL && quoteExpress.Standard_Clause__r.size() > 0 ){
                clauses = quoteExpress.Standard_Clause__r[0].Clause__c;
            }
            Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename="'+filename+'".pdf');
            system.debug('quote exp==' + quoteExpress.Customer__c);
            system.debug('line items===' + quoteLineItems);
            
        }
        
        catch(exception e){
            system.debug('line 35==' + e.getMessage());
        }
        
    }
    
}